services:
  ray-head:
    build: .
    container_name: ray-head
    shm_size: "2gb"
    command: >
      sh -c "ray start --head --port=6379 --dashboard-host=0.0.0.0 &&
             sleep 10 &&
             python etl_ray.py
    ports:
      - "6379:6379"
    volumes:
      - .:/app

  worker1:
    build: .
    container_name: ray-worker-1
    depends_on:
      - ray-head
    command: ray start --address=ray-head:6379 --block
    volumes:
      - .:/app

  worker2:
    build: .
    container_name: ray-worker-2
    depends_on:
      - ray-head
    command: ray start --address=ray-head:6379 --block
    volumes:
      - .:/app

  worker3:
    build: .
    container_name: ray-worker-3
    depends_on:
      - ray-head
    command: ray start --address=ray-head:6379 --block
    volumes:
      - .:/app

  api-server:
    build: .
    container_name: api-fastapi
    command: uvicorn api:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - ray-head
